%% This File is generated by U. Cem Kaya - Spring 2019
%% Plots

function figHandle = plots(mapSize,BuildingCenters,Building_PREM_value,PREM_value,start,finish,X,Y)

figHandle = figure('Visible', 'on');
axis([mapSize(1,1) mapSize(2,1) mapSize(1,2) mapSize(2,2)]);
hold on , grid on


newFigure1 = copyobj(figHandle,'legacy');

ax = gca;               % get the current axis
ax.Clipping = 'off';    % turn clipping off

c1 = plot(BuildingCenters(:,1),BuildingCenters(:,2),'x','LineWidth',2,'color','r','MarkerSize',10);
hold on
set(gca,'ydir','normal');
% grid on
title('\bf Center of Buildings from Building Footprints')
xlabel(' X, km')
ylabel(' Y, km')

legend([c1],'Center of Building','location','northwest');

newFigure2 = copyobj(newFigure1,'legacy');


% % % fncSaveFig(1,pathFigs,'BuildingCenters1',11,6,4)

newFigure3 = copyobj(newFigure1,'legacy');

 
h = surf(X,Y,Building_PREM_value);

caxis([min(Building_PREM_value(:))-.5*range(Building_PREM_value(:)),max(Building_PREM_value(:))]);
set(h, 'EdgeColor', 'k');
set(h, 'LineStyle', '-');
set(h, 'LineWidth', 0.001);
set(h, 'EdgeAlpha',0.0);
set(h, 'FaceLighting','gouraud');
set(h, 'EdgeLighting','gouraud');
material dull
alpha(h,'z')

grid on;
% view(3);
% view(0,90);
title('\bf Probabilistic Risk Exposure Map (Property) - Top View')
xlabel(' X, km')
ylabel(' Y, km')
legend('off');

colormap jet

cb1 = colorbar;
cb1.Limits = [0 max(max(Building_PREM_value))];
cb1.Label.String = 'PREM value';
cb1.Location = 'north';
cb1.Position = [0.15 0.9 0.35 0.02];
cb1.AxisLocation = 'in';

newFigure4 = copyobj(newFigure3,'legacy');

% % % fncSaveFig(1,pathFigs,'BuildingPREM_TOP12',11,6,4)

alpha(h,0.6)

newFigure5 = copyobj(newFigure3,'legacy');

% % % fncSaveFig(1,pathFigs,'BuildingPREM_TOPColored1',11,6,4)

% % newFigure6 = copyobj(newFigure3,'legacy');
% % 
% % view(-22,67);
% % title('\bf Probabilistic Risk Exposure Map (Property) - Isometric View')
% % xlabel(' X, km')
% % ylabel(' Y, km')
% % zlabel(' PREM Value ')
% % legend('off')
% % 
% % fncSaveFig(1,pathFigs,'BuildingPREM_ISO12',18,10,8)

newFigure10 = copyobj(newFigure1,'legacy');

h = surf(X,Y,PREM_value);
% alpha(h,0.7);
caxis([min(PREM_value(:))-.5*range(PREM_value(:)),max(PREM_value(:))]);
set(h, 'EdgeColor', 'k');
set(h, 'LineStyle', '-');
set(h, 'LineWidth', 0.001);
set(h, 'EdgeAlpha',0.0);
set(h, 'FaceLighting','gouraud');
set(h, 'EdgeLighting','gouraud');
material dull
alpha(h,'z')

legend('off');
colormap jet

title('\bf Probabilistic Risk Exposure Map - Top View')
xlabel(' X, km')
ylabel(' Y, km')

cb3 = colorbar;
cb3.Limits = [0 max(max(PREM_value))];
cb3.Label.String = 'PREM value';
cb3.Location = 'north';
cb3.Position = [0.15 0.9 0.35 0.02];
cb3.AxisLocation = 'in';


newFigure11 = copyobj(newFigure10,'legacy');

% % % fncSaveFig(1,pathFigs,'FusedPREM_TOP',11,6,4)

alpha(h,0.6)

newFigure12 = copyobj(newFigure10,'legacy');

% % % premFrame = getframe;
% % % premImg = frame2im(premFrame);

% % % fncSaveFig(1,pathFigs,'FusedPREM_TOPColored11',11,6,4)

newFigure15 = copyobj(newFigure12,'legacy');

premFrame = getframe;
premImg = frame2im(premFrame);

figure(figHandle);
hold on
imagesc([mapSize(1,1) mapSize(2,1)], [mapSize(1,2) mapSize(2,2)], flipud(premImg));
hold on

startHand = plot(start(1) , start(2),'g^','LineWidth',3,'MarkerEdgeColor','g','MarkerSize',6);
hold on
finishHand = plot(finish(1), finish(2),'rs','LineWidth',4,'MarkerEdgeColor','r','MarkerSize',8);
hold on

pause(2)
close([2:10]);
end